version: '3.8'

services:
  securenode:
    image: vankir/securenode:latest
    container_name: securenode
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
       - LICENSE_KEY=securenode2025beta
    deploy:
      resources:
        limits:
          memory: 1G